<?php
try {
	require_once (dirname(__FILE__).'/../DAO/productDAO.php');	require_once (dirname(__FILE__).'/../DAO/scheduleDAO.php');	require_once (dirname(__FILE__).'/../DAO/ticketDAO.php');	require_once (dirname(__FILE__).'/../DAO/pictureDAO.php');	require_once (dirname(__FILE__).'/../DAO/tagDAO.php');
	require_once (dirname(__FILE__).'/../model/product.php');	require_once (dirname(__FILE__).'/../model/schedule.php');	require_once (dirname(__FILE__).'/../model/ticket.php');	require_once (dirname(__FILE__).'/../model/picture.php');	require_once (dirname(__FILE__).'/../model/tag.php');		$pDAO = new productDAO();	$sDAO = new scheduleDAO();	$tDAO = new ticketDAO();	$picDAO = new pictureDAO();	$tagDAO = new tagDAO();
	$strSuccessMsg = "";
	$result = new product ( $_POST['productTitle'], $_POST ['productType'], $_POST ['productCityOfStart'], $_POST ['productCityOfEnd'],			$_POST ['productNumberOfDay'], $_POST ['productDesc'], $_POST ['productTerms'], 			$_POST ['productPriceIncluded'], $_POST ['productPriceNotIncluded'], ' ', $_POST ['productPriceSingle'],			$_POST ['productPriceDouble'], $_POST ['productPriceTriple'], $_POST ['productPriceQuardruple'],			$_POST ['productDiscount'], $_POST ['productCategory'] );	$result->setTax($_POST ['productPriceTax']);	
	if ( isset($_POST['productID'])) {				//$strSuccessMsg = ''.$_POST['cityTagChangeFlag'].'|'.!empty($_POST['productCityTag']);		if ($_POST['cityTagChangeFlag']=="true") {			$existingCityTag = $tagDAO->getTagPID($_POST['productID'], 1);						if (!empty($existingCityTag)) {				$tagDAO->deleteTagPID($_POST['productID'], 1);			}						if (!empty($_POST['productCityTag'])) {				$productCityTags= explode(',',$_POST['productCityTag']);								for($k = 0 ; $k < count($productCityTags) ; $k++) {					$temp = new tag($_POST['productID'], $productCityTags[$k], 1);					//$strSuccessMsg = $strSuccessMsg.'|'.$k.'|'.$productCityTags[$k].' ';					$tagDAO->addTag($temp);				}			}		}				if ($_POST['routeTagChangeFlag']=="true") {			$existingCityTag = $tagDAO->getTagPID($_POST['productID'], 2);						if (!empty($existingCityTag)) {				$tagDAO->deleteTagPID($_POST['productID'], 2);			}						if (!empty($_POST['productRouteTag'])) {				$productRouteTags= explode(',',$_POST['productRouteTag']);								for($k = 0 ; $k < count($productRouteTags) ; $k++) {					$temp = new tag($_POST['productID'], $productRouteTags[$k], 2);					//$strSuccessMsg = $strSuccessMsg.'|'.$k.'|'.$productCityTags[$k].' ';					$tagDAO->addTag($temp);				}			}		}				$schedules = $sDAO->getSchedulePID($_POST['productID']);		$tickets = $tDAO->getTicketPID($_POST['productID']);		$result->setId( $_POST['productID']);
		$delCount = count($_POST['deletePic']); 
		for($i=0; $i<$delCount; $i++) {			$delPic = $picDAO->getPicture($_POST['deletePic'][$i]);			unlink(dirname(__FILE__).'/..'.$delPic->getPictureURL().$delPic->getPictureSavedName());
			$picDAO->deletePicture($_POST['deletePic'][$i]);		}
		if ( isset($_FILES ['productPicture'])) {			$path = "/files/image/";			for ($i=0 ; $i < count($_FILES['productPicture']) ; $i++) {				if (!empty($_FILES['productPicture']['name'][$i])) {					$name = $_FILES['productPicture']['name'][$i];					list ( $txt, $ext ) = explode ( ".", $name );					$savedName = time ().substr((double)microtime(),2).str_pad($_POST['productID'],8,"0",STR_PAD_LEFT). "." . $ext;					$tmp = $_FILES ['productPicture']['tmp_name'][$i];					move_uploaded_file ( $tmp, '..'.$path . $savedName);					$pic = new picture($path,' ',$_POST['productID'], $name, $savedName);					$picDAO->addPictureAdmin($pic);				}			}		}
		if (isset($schedules) && !empty($schedules)) {			$sDAO->deleteSchedulePID($_POST['productID']);		}
		if ( isset($_POST['scheduleDay'])) {			for ($i=0 ; $i < count($_POST['scheduleDay']) ; $i++) {				if (!empty($_POST['scheduleDay'][$i])) {					$day = new schedule($_POST['scheduleTitle'][$i], $_POST['scheduleDay'][$i], $_POST['scheduleDesc'][$i],$_POST['scheduleHotel'][$i],							$_POST['productID'], $_POST['scheduleBreakfast'][$i], $_POST['scheduleLunch'][$i], $_POST['scheduleDinner'][$i]);
					$sDAO->addSchedule($day);				}			}		}
		if (isset($tickets) && !empty($tickets)) {			$tDAO->deleteTicketPID($_POST['productID']);		}
		if ( isset($_POST['ticketTitle'])) {			for ($j=0 ; $j < count($_POST['ticketTitle']) ; $j++) {				if (!empty($_POST['ticketTitle'][$j])) {					$t = new ticket($_POST['ticketTitle'][$j], $_POST['ticketAdult'][$j], $_POST['ticketEnfants'][$j],							$_POST['ticketChildren'][$j], $_POST['ticketTeens'][$j], $_POST['ticketSenior'][$j], $_POST['ticketMandatory'][$j], $_POST['productID']);					$tDAO->addTicket($t);				}			}		} 
		if ( isset($_FILES ['productPdf'])) {			$path = "/files/pdf/";			if (!empty($_FILES['productPdf']['name'])) {				$name = $_FILES['productPdf']['name'];				list ( $txt, $ext ) = explode ( ".", $name );				$savedName = 'ISHALLTRAVEL_'.$_POST['productID'].'.'.$ext;				$tmp = $_FILES ['productPdf']['tmp_name'];				move_uploaded_file ( $tmp, '..'.$path . $savedName);			}			$result->setPdf($path.$savedName);		} else {			$result->setPdf($_POST['productPdfValue']);		}
				$strSuccessMsg = $strSuccessMsg.$pDAO->editProductAdmin($result);
	} else { 		$newID = $pDAO->getNewID();		$strSuccessMsg += 'newID' + $newID;		$result->setId($newID);				if ($_POST['cityTagChangeFlag']=="true") {			if (!empty($_POST['productCityTag'])) {				$productCityTags= explode(',',$_POST['productCityTag']);								for($k = 0 ; $k < count($productCityTags) ; $k++) {					$temp = new tag($newID, $productCityTags[$k], 1);					//$strSuccessMsg = $strSuccessMsg.'|'.$k.'|'.$productCityTags[$k].' ';					$tagDAO->addTag($temp);				}			}		}				if ($_POST['routeTagChangeFlag']=="true") {						if (!empty($_POST['productRouteTag'])) {				$productRouteTags= explode(',',$_POST['productRouteTag']);								for($k = 0 ; $k < count($productRouteTags) ; $k++) {					$temp = new tag($newID, $productRouteTags[$k], 2);					//$strSuccessMsg = $strSuccessMsg.'|'.$k.'|'.$productCityTags[$k].' ';					$tagDAO->addTag($temp);				}			}		}				if ( isset($_FILES ['productPdf'])) {			$path = "/files/pdf/";			if (!empty($_FILES['productPdf']['name'])) {				$name = $_FILES['productPdf']['name'];				list ( $txt, $ext ) = explode ( ".", $name );				$savedName = 'ISHALLTRAVEL_'.$newID.'.'.$ext;				$tmp = $_FILES ['productPdf']['tmp_name'];				move_uploaded_file ( $tmp, '..'.$path . $savedName);			}		}				$result->setPdf($path.$savedName);				$strSuccessMsg += $pDAO->addProductAdmin($result);				if ( isset($_FILES ['productPicture'])) {			$path = "/files/image/";			for ($i=0 ; $i < count($_FILES['productPicture']) ; $i++) {				if (!empty($_FILES['productPicture']['name'][$i])) {					$name = $_FILES['productPicture']['name'][$i];										list ( $txt, $ext ) = explode ( ".", $name );										$savedName = time ().substr((double)microtime(),2).str_pad($newID,8,"0",STR_PAD_LEFT). "." . $ext;					$tmp = $_FILES ['productPicture']['tmp_name'][$i];										move_uploaded_file ( $tmp, '..'.$path . $savedName);					//$picture_URL, $picture_description, $picture_product_ID, $picture_original_name					$pic = new picture($path,' ',$newID, $name, $savedName);					$picDAO->addPictureAdmin($pic);				}			}		}				if ( isset($_POST['scheduleDay'])) {			for ($i=0 ; $i < count($_POST['scheduleDay']) ; $i++) {				//echo '['.sizeof($_POST['scheduleTitle']).']';				$day = new schedule($_POST['scheduleTitle'][$i], $_POST['scheduleDay'][$i], $_POST['scheduleDesc'][$i],$_POST['scheduleHotel'][$i],						$newID, $_POST['scheduleBreakfast'][$i], $_POST['scheduleLunch'][$i], $_POST['scheduleDinner'][$i]);				$sDAO->addSchedule($day);			}		}				if ( isset($_POST['ticketTitle'])) {			for ($j=0 ; $j < count($_POST['ticketTitle']) ; $j++) {				//$title,$adult,$enfants,$child,$teen,$senior,$mandatory,$productID				$t = new ticket($_POST['ticketTitle'][$j], $_POST['ticketAdult'][$j], $_POST['ticketEnfants'][$j],						$_POST['ticketChildren'][$j], $_POST['ticketTeens'][$j], $_POST['ticketSenior'][$j], $_POST['ticketMandatory'][$j], $newID);				$tDAO->addTicket($t);			}		}	}
	echo $strSuccessMsg;	} catch ( Exception $e ) {		echo $e->getMessage ();}
?>